src/Personalized365.Web/ViewModels/DialogBoxViewModel.cs
namespace Personalized365.Web.ViewModels
{
    public class DialogBoxViewModel
    {
        public string Message { get; set; }
    }
}

src/Personalized365.Web/ViewModels/EmailViewModel.cs
namespace Personalized365.Web.ViewModels
{
    public class EmailViewModel
    {
        public string Subject { get; set; }

        public string Body { get; set; }

        public DateTime ReceivedUtcDateTime { get; set; }
    }
}

src/Personalized365.Web/Pages/Email.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Personalized365.Web.Pages
{
    public class EmailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Personalized365.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Personalized365.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/Personalized365.Web/Pages/Files.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using Personalized365.Web.Graph;
using System.Net.Mime;

namespace Personalized365.Web.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    // Max supported upload size is 100MB
    [RequestFormLimits(MultipartBodyLengthLimit = 100000000)]
    [RequestSizeLimit(100000000)]
    public class FilesModel : PageModel
    {
        private readonly ILogger<FilesModel> _logger;
        private readonly GraphFilesClient _graphFilesClient;

        [BindProperty]
        public IFormFile UploadedFile { get; set; }
        public IDriveItemChildrenCollectionPage Files { get; private set; }

        public FilesModel(
            ILogger<FilesModel> logger,
            GraphFilesClient graphFilesClient)
        {
            _graphFilesClient = graphFilesClient;
            _logger = logger;
        }

        public async Task OnGetAsync()
        {
            Files = await _graphFilesClient.GetFiles();
        }

        public async Task OnPostAsync()
        {
            if (UploadedFile == null || UploadedFile.Length == 0)
            {
                return;
            }

            _logger.LogInformation($"Uploading {UploadedFile.FileName}");

            using (var stream = new MemoryStream())
            {
                await UploadedFile.CopyToAsync(stream);
                await _graphFilesClient.UploadFile(UploadedFile.FileName, stream);
            }

            await OnGetAsync();
        }

        public async Task<FileStreamResult> OnGetDownloadFile(string id, string name)
        {
            var stream = await _graphFilesClient.DownloadFile(id);
            return File(stream, MediaTypeNames.Application.Octet, name);
        }
    }
}

src/Personalized365.Web/Pages/Index.cshtml.cs
using Azure;
using Azure.AI.TextAnalytics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using Personalized365.Web.Graph;
using Personalized365.Web.ViewModels;

namespace Personalized365.Web.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly GraphProfileClient _graphProfileClient;
        private readonly GraphEmailClient _graphEmailClient;
        private readonly GraphCalendarClient _graphCalendarClient;
        private readonly GraphTodoClient _graphTodoClient;
        private readonly AppSettings appSettings;

        public string UserDisplayName { get; private set; } = "";
        public string? UserPhoto { get; private set; }

        public IEnumerable<Message> Messages { get; private set; }
        public List<SummarizedMessage> SummarizedMessages { get; private set; }

        private MailboxSettings MailboxSettings { get; set; }
        public IEnumerable<Event> Events { get; private set; }

        public IEnumerable<TodoTask> TodoTasks { get; private set; }

        public IndexModel(
            ILogger<IndexModel> logger,
            ITokenAcquisition tokenAcquisition,
            GraphProfileClient graphProfileClient,
            GraphEmailClient graphEmailClient,
            GraphCalendarClient graphCalendarClient,
            GraphTodoClient graphTodoClient)
        {
            _logger = logger;
            _graphProfileClient = graphProfileClient;
            _graphEmailClient = graphEmailClient;
            _graphCalendarClient = graphCalendarClient;
            _graphTodoClient = graphTodoClient;

            appSettings = AppSettings.Load();
        }

        public async Task OnGetAsync()
        {
            var user = await _graphProfileClient.GetUserProfile();
            UserDisplayName = user.DisplayName.Split(' ')[0];
            UserPhoto = await _graphProfileClient.GetUserProfileImage();
            await GetEmailAsync();
            await GetCalendarEventAsync();
            await GetTodoAsync();
        }

        #region Email

        private async Task GetEmailAsync()
        {
            Messages = await _graphEmailClient.GetUserMessages();
            SummarizedMessages = new List<SummarizedMessage>();

            var textAnalyticsClient = GetTextAnalyticsClient();

            foreach (var message in Messages)
            {
                SummarizedMessages.Add(new SummarizedMessage
                {
                    Id = message.Id,
                    Subject = message.Subject,
                    ReceivedUtcDateTime = message.ReceivedDateTime.GetValueOrDefault().UtcDateTime,
                    BodyPreview = message.BodyPreview,
                    SummarySentences = await GetSummaryAsync(textAnalyticsClient, message.BodyPreview)
                });
            }
        }

        private TextAnalyticsClient GetTextAnalyticsClient()
        {
            var credential = new AzureKeyCredential(appSettings.TextAnalyticsCredential);
            var endpoint = new Uri(appSettings.TextAnalyticsEndpoint);

            return new TextAnalyticsClient(endpoint, credential);
        }

        private async Task<IList<string>> GetSummaryAsync(TextAnalyticsClient client, string emailBody)
        {
            var sentances = new List<string>();

            // Prepare analyze operation input. You can add multiple documents to this list and perform the same
            // operation to all of them.
            var batchInput = new List<string>
            {
                emailBody
            };

            TextAnalyticsActions actions = new TextAnalyticsActions()
            {
                ExtractSummaryActions = new List<ExtractSummaryAction>() { new ExtractSummaryAction() }
            };

            // Start analysis process.
            AnalyzeActionsOperation operation = await client.StartAnalyzeActionsAsync(batchInput, actions);
            await operation.WaitForCompletionAsync();
            // View operation status.
            Console.WriteLine($"AnalyzeActions operation has completed");
            Console.WriteLine();

            Console.WriteLine($"Created On   : {operation.CreatedOn}");
            Console.WriteLine($"Expires On   : {operation.ExpiresOn}");
            Console.WriteLine($"Id           : {operation.Id}");
            Console.WriteLine($"Status       : {operation.Status}");

            Console.WriteLine();
            // View operation results.
            await foreach (AnalyzeActionsResult documentsInPage in operation.Value)
            {
                IReadOnlyCollection<ExtractSummaryActionResult> summaryResults = documentsInPage.ExtractSummaryResults;

                foreach (ExtractSummaryActionResult summaryActionResults in summaryResults)
                {
                    if (summaryActionResults.HasError)
                    {
                        Console.WriteLine($"  Error!");
                        Console.WriteLine($"  Action error code: {summaryActionResults.Error.ErrorCode}.");
                        Console.WriteLine($"  Message: {summaryActionResults.Error.Message}");
                        continue;
                    }

                    foreach (ExtractSummaryResult documentResults in summaryActionResults.DocumentsResults)
                    {
                        if (documentResults.HasError)
                        {
                            Console.WriteLine($"  Error!");
                            Console.WriteLine($"  Document error code: {documentResults.Error.ErrorCode}.");
                            Console.WriteLine($"  Message: {documentResults.Error.Message}");
                            continue;
                        }

                        Console.WriteLine($"  Extracted the following {documentResults.Sentences.Count} sentence(s):");
                        Console.WriteLine();

                        foreach (SummarySentence sentence in documentResults.Sentences)
                        {
                            Console.WriteLine($"  Sentence: {sentence.Text}");
                            Console.WriteLine();

                            sentances.Add(sentence.Text);
                        }
                    }
                }
            }

            return sentances;
        }

        public async Task<PartialViewResult> OnGetViewEmail(string id)
        {
            var email = (await _graphEmailClient.GetUserMessages())
                .First(model => model.Id == id);

            return new PartialViewResult
            {
                ViewName = "ViewEmail",
                ViewData = new ViewDataDictionary<EmailViewModel>(ViewData, new EmailViewModel
                {
                    Subject = email.Subject,
                    Body = email.BodyPreview,
                    ReceivedUtcDateTime = email.ReceivedDateTime.GetValueOrDefault().UtcDateTime
                })
            };
        }

        public async Task<PartialViewResult> OnPostAddEmailToDo(string id)
        {
            var email = (await _graphEmailClient.GetUserMessages())
                .First(model => model.Id == id);

            var todoTask = new TodoTask
            {
                Title = $"From email: {email.Subject}",
                Categories = new List<string>
                {
                    "Important"
                },
                Importance = Importance.High
            };

            await _graphTodoClient.AddTodo(todoTask);
            await GetTodoAsync();

            return new PartialViewResult
            {
                ViewName = "DialogBox",
                ViewData = new ViewDataDictionary<DialogBoxViewModel>(ViewData, new DialogBoxViewModel
                {
                    Message = "Added successfully."
                })
            };
        }

        #endregion

        #region Calendar Event

        private async Task GetCalendarEventAsync()
        {
            MailboxSettings = await _graphCalendarClient.GetUserMailboxSettings();
            var userTimeZone = (string.IsNullOrEmpty(MailboxSettings.TimeZone))
                ? "Pacific Standard Time"
                : MailboxSettings.TimeZone;
            Events = await _graphCalendarClient.GetEvents(userTimeZone);
        }

        public string FormatDateTimeTimeZone(DateTimeTimeZone value)
        {
            // Parse the date/time string from Graph into a DateTime
            var graphDatetime = value.DateTime;
            if (DateTime.TryParse(graphDatetime, out DateTime dateTime))
            {
                var dateTimeFormat = $"{MailboxSettings.DateFormat} {MailboxSettings.TimeFormat}".Trim();
                if (!string.IsNullOrEmpty(dateTimeFormat))
                {
                    return dateTime.ToString(dateTimeFormat);
                }
                else
                {
                    return $"{dateTime.ToShortDateString()} {dateTime.ToShortTimeString()}";
                }
            }
            else
            {
                return graphDatetime;
            }
        }

        #endregion

        #region To do

        private async Task GetTodoAsync()
        {
            TodoTasks = await _graphTodoClient.GetTodos();
        }

        #endregion
    }
}

src/Personalized365.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Personalized365.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Personalized365.Web/Pages/Teams.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using Personalized365.Web.Graph;

namespace Personalized365.Web.Pages
{
    [AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]
    public class TeamsModel : PageModel
    {
        private readonly GraphTeamClient _graphTeamClient;

        public IEnumerable<Team> MyTeams { get; private set; }

        public TeamsModel(GraphTeamClient graphTeamClient)
        {
            _graphTeamClient = graphTeamClient;
        }

        public async Task OnGetAsync()
        {
            MyTeams = await _graphTeamClient.GetMyTeams();
        }
    }
}

src/Personalized365.Web/Pages/DialogBox.cshtml
@model ViewModels.DialogBoxViewModel

<p>@Model.Message</p>

src/Personalized365.Web/Pages/Email.cshtml
@page
@model Personalized365.Web.Pages.EmailModel
@{
}

src/Personalized365.Web/Pages/Files.cshtml
@page
@model FilesModel
@{
    ViewData["Title"] = "Upload File";
}

<div>
    <h1>Files</h1>
    @if (User.Identity.IsAuthenticated)
    {
        <div>
            <!-- Add for file download -->
            @if (Model.Files != null && Model.Files.Count > 0)
            {
                <br />
                <label>Files in your OneDrive root folder:</label> @Model.Files.Count()
                <ul id="downloadLinks">

                    @* Add foreach here *@
                    @foreach (var file in Model.Files)
                    {
                        @if (file.Folder == null && file.Package == null)
                        {
                            <li>
                                <a asp-page-handler="DownloadFile"
                   asp-route-name="@file.Name"
                   asp-route-id="@file.Id">
                                    @file.Name
                                </a>
                            </li>
                        }

                        @* Add foreach closing bracket here *@
                    }
                </ul>
            }
            else
            {
                <div>No files found</div>
            }
        </div>

        <br />

        <br />
        <h3>Upload File</h3>
        <hr />
        <form method="post" enctype="multipart/form-data">
            <input asp-for="UploadedFile" type="file">
            <input type="submit" value="Upload File">
        </form>
    }
    else
    {
        <a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>
    }
</div>

src/Personalized365.Web/Pages/Index.cshtml
@page
@using Microsoft.Graph
@model IndexModel
@{
    ViewData["Title"] = "Home";

    string GetTaskPriorityLabel(TodoTask task)
    {
        if (task.Importance == null)
            return "Priority Level: NA";

        return $"Priority Level: {Enum.GetName<Importance>(task.Importance.Value)}";
    }
}

<div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <h2>Email Summary</h2>
                    @if (Model.SummarizedMessages != null && Model.SummarizedMessages.Any())
                    {
                        @foreach (var message in Model.SummarizedMessages)
                        {
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        @message.Subject
                                    </h5>
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        @message.ReceivedUtcDateTime
                                    </h6>
                                    <p class="card-text">
                                        <ul>
                                            @foreach (var sentence in message.SummarySentences)
                                            {
                                                <li>@sentence</li>
                                            }
                                        </ul>
                                    </p>

                                    <button data-id="@message.Id" class="btn btn-primary btn-sm view-email">View</button>
                                    <button data-id="@message.Id" class="btn btn-primary btn-sm add-to-do">Add to To Do</button>
                                </div>
                            </div>
                            <br />
                        }
                    }
                    else
                    {
                        <div>No Messages found</div>
                    }
                </div>

                <div class="col-4">
                    @*Todo*@
                    <h2>To do</h2>
                    @if (Model.TodoTasks != null && Model.TodoTasks.Any())
                    {
                        <ul class="list-group">
                            @foreach (var todo in Model.TodoTasks)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                    <div class="ms-2 me-auto">
                                        <div class="fw-bold">@todo.Title</div>
                                        <small>@GetTaskPriorityLabel(todo)</small>
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <div>No Tasks found</div>
                    }

                    <hr />
                    @*Calendar Events*@
                    <h2>Calendar Events</h2>
                    @if (Model.Events != null && Model.Events.Any())
                    {
                        <ul class="list-group">
                            @foreach (var evt in Model.Events)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                    <div class="ms-2 me-auto">
                                        <div class="fw-bold">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-event" viewBox="0 0 16 16">
                                                <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z" />
                                                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z" />
                                            </svg>
                                            @evt.Subject
                                        </div>
                                        <small>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
                                                <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                                                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                                            </svg>
                                            @Model.FormatDateTimeTimeZone(evt.Start) - @Convert.ToDateTime(Model.FormatDateTimeTimeZone(evt.End)).ToString("hh:mm tt")
                                        </small>
                                    </div>
                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <div>No calendar events found</div>
                    }
                </div>
            </div>
        </div>

        @Html.AntiForgeryToken()

        <div id="viewEmailModal" class="modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">View Email</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <partial name="_DialogBoxPartial" />
    }
    else
    {
        <a class="btn btn-primary btn-large" href="https://localhost:5001/signin-oidc">Click here to sign in</a>
    }
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $(".view-email").click(function () {
                var id = $(this).attr("data-id");

                $.ajax({
                    type: "GET",
                    url: "/Index?handler=ViewEmail",
                    data: { "id": id },
                    success: function (response) {
                        $("#viewEmailModal").find(".modal-body").html(response);
                        $("#viewEmailModal").modal('show');
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });

            $(".add-to-do").click(function () {
                var id = $(this).attr("data-id");

                $.ajax({
                    type: "POST",
                    url: "/Index?handler=AddEmailToDo",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    data: { "id": id },
                    success: function (response) {
                        $("#dialogBoxModal").find(".modal-body").html(response);
                        $("#dialogBoxModal").modal('show');
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });
        });
    </script>
}

src/Personalized365.Web/Pages/Teams.cshtml
@page
@using Microsoft.Graph
@model Personalized365.Web.Pages.TeamsModel
@{
    ViewData["Title"] = "Teams";
}

<div>
    @if (User.Identity.IsAuthenticated)
    {
        @if (Model.MyTeams != null && Model.MyTeams.Any())
        {
            <h1>Teams</h1>
            <div class="accordion accordion-flush" id="accordionFlush">
                @foreach (var team in Model.MyTeams)
                {
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-heading-@team.Id">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-@team.Id" aria-expanded="false" aria-controls="flush-collapse-@team.Id">
                                @team.DisplayName
                            </button>
                        </h2>
                        <div id="flush-collapse-@team.Id" class="accordion-collapse collapse" aria-labelledby="flush-heading-@team.Id" data-bs-parent="#accordionFlush">
                            <div class="accordion-body">
                                @if (team.AllChannels != null && team.AllChannels.Any())
                                {
                                    <h5>Channels</h5>
                                    <ul class="list-group">
                                        @foreach (var channel in team.AllChannels)
                                        {
                                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                                <div class="ms-2 me-auto">
                                                    <div class="fw-bold">@channel.DisplayName</div>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                }
                                else
                                {
                                    <div>No Channels found</div>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
        else
        {
            <div>No Teams found</div>
        }
    }
    else
    {
        <a class="btn btn-primary btn-large" href="https://localhost:5001/signin-oidc">Click here to sign in</a>
    }
</div>

src/Personalized365.Web/Pages/ViewEmail.cshtml
@model ViewModels.EmailViewModel

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            @Model.Subject
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
            @Model.ReceivedUtcDateTime
        </h6>
        <p class="card-text">
            @Model.Body
        </p>
    </div>
</div>